/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import ComunicacionesDAO.EmpleadoDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;

/**
 *
 * @author fernan
 */
public class EmpleadoFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmpleadoFrame
     */
    public EmpleadoFrame() {
        initComponents();
        cargarRol();
        cargarJornada();
        cargarTabla();
    }
    
    
    private void cargarRol() {

    cmbRol.removeAllItems();

    cmbRol.addItem("MESERO");
    cmbRol.addItem("COCINA");
    cmbRol.addItem("BARISTA");
    cmbRol.addItem("ADMINISTRADOR");

}
    
    private void cargarJornada() {

    cmbJornada.removeAllItems();

    cmbJornada.addItem("MATUTINA");
    cmbJornada.addItem("VESPERTINA");
    cmbJornada.addItem("NOCTURNA");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbJornada = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollEmpleados = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese DPI: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, 30));

        txtDpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDpiActionPerformed(evt);
            }
        });
        getContentPane().add(txtDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 300, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 300, 40));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione un Rol: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 300, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccione una Jornada: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        cmbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 310, 30));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese Salario: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, 30));

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 300, 40));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese Fecha: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, 300, 40));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 750, 100, 50));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 750, 100, 50));

        btnDeshabilitar.setText("Deshabilitar/Activar");
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 750, -1, 50));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 760, 100, 40));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DPI", "Nombre", "Rol", "Jornada", "Salario", "Fecha", "Estado"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        scrollEmpleados.setViewportView(tblEmpleados);

        jScrollPane1.setViewportView(scrollEmpleados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 580, 140));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 760, 340, 50));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("GESTION DE EMPLEADOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDpiActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
     if (!validarDatos()) {
        return;
    }

    String dpi = txtDpi.getText().trim();
    String nombre = txtNombre.getText().trim();
    String rol = cmbRol.getSelectedItem().toString();
    String jornada = cmbJornada.getSelectedItem().toString();
    double salario = Double.parseDouble(txtSalario.getText().trim());
    String fecha = txtFecha.getText().trim();

    EmpleadoDAO empleadoDAO = new EmpleadoDAO();

    // Verificar si el DPI ya existe
    if (empleadoDAO.existeEmpleado(dpi)) {

        JOptionPane.showMessageDialog(
                this,
                "El DPI ingresado ya está registrado."
        );

        txtDpi.requestFocus();

        return;
    }

    Empleado empleado = new Empleado(
            dpi,
            nombre,
            rol,
            jornada,
            salario,
            fecha,
            true
    );

    boolean registrado =
            empleadoDAO.insertarEmpleado(empleado);

    if (registrado) {

        JOptionPane.showMessageDialog(
                this,
                "Empleado registrado correctamente."
        );

        // Actualizar la tabla
        cargarTabla();

        // Limpiar los campos
        limpiarCampos();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar el empleado."
        );
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cargarTabla() {

    DefaultTableModel modelo =
            (DefaultTableModel) tblEmpleados.getModel();

    modelo.setRowCount(0);

    EmpleadoDAO empleadoDAO =
            new EmpleadoDAO();

    try {

        ResultSet resultado =
                empleadoDAO.obtenerEmpleados();

        while (resultado.next()) {

            Object[] fila = {

                resultado.getString("dpi"),
                resultado.getString("nombre"),
                resultado.getString("rol"),
                resultado.getString("jornada"),
                resultado.getDouble("salario"),
                resultado.getDate("fecha_contratacion"),
                resultado.getBoolean("estado")
            };

            modelo.addRow(fila);
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al cargar los empleados."
        );

        e.printStackTrace();
    }
}
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if(!validarDatos()){
            return;
        }
        String dpi = txtDpi.getText().trim();
        String nombre = txtNombre.getText().trim();
        String rol = cmbRol.getSelectedItem().toString();
        String jornada = cmbJornada.getSelectedItem().toString();
        Double salario = Double.parseDouble(txtSalario.getText());
        String fecha = txtFecha.getText().trim();
        
        Empleado empleado = new Empleado(
                dpi,
                nombre,
                rol,
                jornada,
                salario,
                fecha,
                true
        );
        
        EmpleadoDAO empleadoDAO = new EmpleadoDAO();
            empleadoDAO.actualizarEmpleado(empleado);
            cargarTabla();
            limpiarCampos();
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        if (txtDpi.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un empleado de la tabla"
        );

        return;
    }

    EmpleadoDAO empleadoDAO = new EmpleadoDAO();

    String dpi = txtDpi.getText().trim();

    boolean estadoActual =
            empleadoDAO.obtenerEstadoEmpleado(dpi);

    String mensaje;

    if (estadoActual) {

        mensaje = "¿Desea deshabilitar este empleado?";

    } else {

        mensaje = "¿Desea habilitar este empleado?";

    }

    int respuesta = JOptionPane.showConfirmDialog(
            this,
            mensaje,
            "Confirmación",
            JOptionPane.YES_NO_OPTION
    );

    if (respuesta != JOptionPane.YES_OPTION) {
        return;
    }

    empleadoDAO.cambiarEstadoEmpleado(
            dpi,
            !estadoActual
    );

    cargarTabla();
    limpiarCampos();


        
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
        int fila = tblEmpleados.getSelectedRow();
        
        txtDpi.setText(tblEmpleados.getValueAt(fila, 0).toString());
        txtNombre.setText(tblEmpleados.getValueAt(fila, 1).toString());
        
        cmbRol.setSelectedItem(tblEmpleados.getValueAt(fila, 2).toString());
        cmbJornada.setSelectedItem(tblEmpleados.getValueAt(fila, 3).toString());
        
        txtSalario.setText(tblEmpleados.getValueAt(fila, 4).toString());
        txtFecha.setText(tblEmpleados.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tblEmpleadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbJornada;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollEmpleados;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtDpi;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
    private boolean validarDatos() {

    if (txtDpi.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar el DPI."
        );

        txtDpi.requestFocus();
        return false;
    }

    if (txtNombre.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar el nombre."
        );

        txtNombre.requestFocus();
        return false;
    }

    if (txtSalario.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar el salario."
        );

        txtSalario.requestFocus();
        return false;
    }

    double salario;

    try {

        salario = Double.parseDouble(txtSalario.getText());

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "El salario debe ser un número."
        );

        txtSalario.requestFocus();
        return false;

    }

    if (salario <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "El salario debe ser mayor que cero."
        );

        txtSalario.requestFocus();
        return false;
    }

    if (txtFecha.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar la fecha de contratación."
        );

        txtFecha.requestFocus();
        return false;
    }

    return true;

}
    private void limpiarCampos() {

    txtDpi.setText("");
    txtNombre.setText("");
    txtSalario.setText("");
    txtFecha.setText("");

    cmbRol.setSelectedIndex(0);
    cmbJornada.setSelectedIndex(0);

    txtDpi.requestFocus();

}
}
