/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author fernan
 */
public class FrmVentaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVentaPrincipal.class.getName());

    /**
     * Creates new form FrmVentaPrincipal
     */
    public FrmVentaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        empleado = new javax.swing.JMenu();
        menuEmpleado = new javax.swing.JMenuItem();
        Nomina = new javax.swing.JMenu();
        menuNomina = new javax.swing.JMenuItem();
        inventario = new javax.swing.JMenu();
        menuInsumo = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenu();
        menuProducto = new javax.swing.JMenuItem();
        menuReceta = new javax.swing.JMenuItem();
        mesa = new javax.swing.JMenu();
        menuMesa = new javax.swing.JMenuItem();
        cuenta = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenuItem();
        menuDetalleCuenta = new javax.swing.JMenuItem();
        reportes = new javax.swing.JMenu();
        menuFlujoCaja = new javax.swing.JMenuItem();
        menuProductosVendidos = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBeans Cafe´");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 580));

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        empleado.setText("Personal");
        empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoActionPerformed(evt);
            }
        });

        menuEmpleado.setText("Gestionar Empleados");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        empleado.add(menuEmpleado);

        jMenuBar1.add(empleado);

        Nomina.setText("Nominas");

        menuNomina.setText("Gestionar Nominas");
        Nomina.add(menuNomina);

        jMenuBar1.add(Nomina);

        inventario.setText("Inventario");

        menuInsumo.setText("Insumos");
        inventario.add(menuInsumo);

        menuCompra.setText("Compras");
        inventario.add(menuCompra);

        jMenuBar1.add(inventario);

        Menu.setText("Menu");

        menuProducto.setText("Productos");
        Menu.add(menuProducto);

        menuReceta.setText("Recetas");
        Menu.add(menuReceta);

        jMenuBar1.add(Menu);

        mesa.setText("Mesas");

        menuMesa.setText("Gestionar Mesas");
        mesa.add(menuMesa);

        jMenuBar1.add(mesa);

        cuenta.setText("Cuenta");

        menuCuenta.setText("Abrir Cuenta");
        cuenta.add(menuCuenta);

        menuDetalleCuenta.setText("Detalle Cuenta");
        cuenta.add(menuDetalleCuenta);

        jMenuBar1.add(cuenta);

        reportes.setText("Reportes");

        menuFlujoCaja.setText("Flujo De La Caja");
        reportes.add(menuFlujoCaja);

        menuProductosVendidos.setText("Productos  mas vendidos¨");
        reportes.add(menuProductosVendidos);

        menuStock.setText("Insumos bajo Stock");
        reportes.add(menuStock);

        jMenuBar1.add(reportes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoActionPerformed

    }//GEN-LAST:event_empleadoActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
       EmpleadoFrame empleado = new EmpleadoFrame();

    desktopPane.add(empleado);

    empleado.setVisible(true);
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVentaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenu Nomina;
    private javax.swing.JMenu cuenta;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu empleado;
    private javax.swing.JMenu inventario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuCuenta;
    private javax.swing.JMenuItem menuDetalleCuenta;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenuItem menuFlujoCaja;
    private javax.swing.JMenuItem menuInsumo;
    private javax.swing.JMenuItem menuMesa;
    private javax.swing.JMenuItem menuNomina;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuProductosVendidos;
    private javax.swing.JMenuItem menuReceta;
    private javax.swing.JMenuItem menuStock;
    private javax.swing.JMenu mesa;
    private javax.swing.JMenu reportes;
    // End of variables declaration//GEN-END:variables
}
