/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author fernan
 */
public class FrmVentaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVentaPrincipal.class.getName());

    /**
     * Creates new form FrmVentaPrincipal
     */
    public FrmVentaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        empleado = new javax.swing.JMenu();
        menuEmpleado = new javax.swing.JMenuItem();
        Nomina = new javax.swing.JMenu();
        menuNomina = new javax.swing.JMenuItem();
        inventario = new javax.swing.JMenu();
        menuInsumo = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenu();
        menuProducto = new javax.swing.JMenuItem();
        menuReceta = new javax.swing.JMenuItem();
        mesa = new javax.swing.JMenu();
        menuMesa = new javax.swing.JMenuItem();
        cuenta = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenuItem();
        menuDetalleCuenta = new javax.swing.JMenuItem();
        reportes = new javax.swing.JMenu();
        menuFlujoCaja = new javax.swing.JMenuItem();
        menuProductosVendidos = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBeans Cafe´");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N

        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 980));

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        empleado.setText("Personal");
        empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoActionPerformed(evt);
            }
        });

        menuEmpleado.setText("Gestionar Empleados");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        empleado.add(menuEmpleado);

        jMenuBar1.add(empleado);

        Nomina.setText("Nominas");

        menuNomina.setText("Gestionar Nominas");
        menuNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNominaActionPerformed(evt);
            }
        });
        Nomina.add(menuNomina);

        jMenuBar1.add(Nomina);

        inventario.setText("Inventario");

        menuInsumo.setText("Insumos");
        menuInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsumoActionPerformed(evt);
            }
        });
        inventario.add(menuInsumo);

        menuCompra.setText("Compras");
        menuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompraActionPerformed(evt);
            }
        });
        inventario.add(menuCompra);

        jMenuBar1.add(inventario);

        Menu.setText("Menu");

        menuProducto.setText("Productos");
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        Menu.add(menuProducto);

        menuReceta.setText("Recetas");
        menuReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecetaActionPerformed(evt);
            }
        });
        Menu.add(menuReceta);

        jMenuBar1.add(Menu);

        mesa.setText("Mesas");

        menuMesa.setText("Gestionar Mesas");
        menuMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMesaActionPerformed(evt);
            }
        });
        mesa.add(menuMesa);

        jMenuBar1.add(mesa);

        cuenta.setText("Cuenta");

        menuCuenta.setText("Abrir Cuenta");
        menuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentaActionPerformed(evt);
            }
        });
        cuenta.add(menuCuenta);

        menuDetalleCuenta.setText("Detalle Cuenta");
        menuDetalleCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDetalleCuentaActionPerformed(evt);
            }
        });
        cuenta.add(menuDetalleCuenta);

        jMenuBar1.add(cuenta);

        reportes.setText("Reportes");

        menuFlujoCaja.setText("Flujo De La Caja");
        menuFlujoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFlujoCajaActionPerformed(evt);
            }
        });
        reportes.add(menuFlujoCaja);

        menuProductosVendidos.setText("Productos  mas vendidos¨");
        menuProductosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosVendidosActionPerformed(evt);
            }
        });
        reportes.add(menuProductosVendidos);

        menuStock.setText("Insumos bajo Stock");
        menuStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStockActionPerformed(evt);
            }
        });
        reportes.add(menuStock);

        jMenuBar1.add(reportes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoActionPerformed

    }//GEN-LAST:event_empleadoActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
       EmpleadoFrame empleado = new EmpleadoFrame();

        desktopPane.add(empleado);

        empleado.setVisible(true);
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNominaActionPerformed
        NominaFrame nomina = new NominaFrame();
        desktopPane.add(nomina);
        nomina.setVisible(true);
    }//GEN-LAST:event_menuNominaActionPerformed

    private void menuInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsumoActionPerformed
        // TODO add your handling code here:
        InsumoFrame insumo = new InsumoFrame();
        desktopPane.add(insumo);
        insumo.setVisible(true);
    }//GEN-LAST:event_menuInsumoActionPerformed

    private void menuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompraActionPerformed
        // TODO add your handling code here:
        CompraInsumoFrame compraInsumo = new CompraInsumoFrame();
        desktopPane.add(compraInsumo);
        compraInsumo.setVisible(true);
    }//GEN-LAST:event_menuCompraActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
        // TODO add your handling code here:
        ProductoFrame producto = new ProductoFrame();
        desktopPane.add(producto);
        producto.setVisible(true);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void menuRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecetaActionPerformed
        // TODO add your handling code here:
        RecetaFrame receta = new RecetaFrame();
        desktopPane.add(receta);
        receta.setVisible(true);
    }//GEN-LAST:event_menuRecetaActionPerformed

    private void menuMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMesaActionPerformed
        // TODO add your handling code here:
        MesaFrame mesa = new MesaFrame();
        desktopPane.add(mesa);
        mesa.setVisible(true);
    }//GEN-LAST:event_menuMesaActionPerformed

    private void menuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentaActionPerformed
        // TODO add your handling code here:
        CuentaFrame cuenta = new CuentaFrame();
        desktopPane.add(cuenta);
        cuenta.setVisible(true);
    }//GEN-LAST:event_menuCuentaActionPerformed

    private void menuDetalleCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDetalleCuentaActionPerformed
        // TODO add your handling code here:
        DetalleCuentaFrame detalleCuenta = new DetalleCuentaFrame();
        desktopPane.add(detalleCuenta);
        detalleCuenta.setVisible(true);
    }//GEN-LAST:event_menuDetalleCuentaActionPerformed

    private void menuFlujoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFlujoCajaActionPerformed
        // TODO add your handling code here:
        ReporteFrame reporte = new ReporteFrame();
        //metodo para los reportes
        desktopPane.add(reporte);
        reporte.setVisible(true);
    }//GEN-LAST:event_menuFlujoCajaActionPerformed

    private void menuProductosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosVendidosActionPerformed
        // TODO add your handling code here:
         ReporteFrame reporte = new ReporteFrame();
        //metodo para los reportes
        desktopPane.add(reporte);
        reporte.setVisible(true);
    }//GEN-LAST:event_menuProductosVendidosActionPerformed

    private void menuStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockActionPerformed
        // TODO add your handling code here:
         ReporteFrame reporte = new ReporteFrame();
        //metodo para los reportes
        desktopPane.add(reporte);
        reporte.setVisible(true);
    }//GEN-LAST:event_menuStockActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenu Nomina;
    private javax.swing.JMenu cuenta;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu empleado;
    private javax.swing.JMenu inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuCuenta;
    private javax.swing.JMenuItem menuDetalleCuenta;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenuItem menuFlujoCaja;
    private javax.swing.JMenuItem menuInsumo;
    private javax.swing.JMenuItem menuMesa;
    private javax.swing.JMenuItem menuNomina;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuProductosVendidos;
    private javax.swing.JMenuItem menuReceta;
    private javax.swing.JMenuItem menuStock;
    private javax.swing.JMenu mesa;
    private javax.swing.JMenu reportes;
    // End of variables declaration//GEN-END:variables
}
