/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import ComunicacionesDAO.NominaDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class NominaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NominaFrame
     */
    public NominaFrame() {
        initComponents();
        setClosable(true);
        cargarCombos();
        NominaDAO dao = new NominaDAO();

        dao.generarNominasAutomaticamente();

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGenerarNomina = new javax.swing.JButton();
        btnPagarNomina = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNomina = new javax.swing.JTable();
        cmbEmpleado = new javax.swing.JComboBox<>();
        cmbTipoPago = new javax.swing.JComboBox<>();
        txtFechaEmision = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GESTION DE NOMINAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DPI Empleado: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Pago: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Emision:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Monto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        btnGenerarNomina.setText("Generar Nomina");
        btnGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarNominaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, 50));

        btnPagarNomina.setText("Pagar Nomina");
        btnPagarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarNominaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagarNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 160, 50));

        tblNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "DPI", "Fecha", "Tipo", "Monto", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNomina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNominaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNomina);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 590, 230));

        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 40));

        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 160, 40));
        getContentPane().add(txtFechaEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 160, 40));

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 160, 30));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 160, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnPagarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarNominaActionPerformed
        // TODO add your handling code here:

        int filaSeleccionada = tblNomina.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una nómina de la tabla."
            );
            return;
        }

        // Obtener código de nómina
        int codigoNomina = Integer.parseInt(tblNomina.getValueAt(filaSeleccionada,0).toString());
        // Obtener estado
        String estado = tblNomina.getValueAt(filaSeleccionada,5).toString();

        // Verificar que esté pendiente
        if (!estado.equals("PENDIENTE")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Esta nómina ya fue pagada."
            );

            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(
                        this,
                        "¿Desea pagar esta nómina?",
                        "Confirmar pago",
                        JOptionPane.YES_NO_OPTION
                );

        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }

        NominaDAO dao = new NominaDAO();
        boolean pagada = dao.pagarNomina(codigoNomina);

        if (pagada) {

            JOptionPane.showMessageDialog(
                    this,
                    "Nómina pagada correctamente."
            );

            cargarTabla();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo pagar la nómina."
            );
        }
    }//GEN-LAST:event_btnPagarNominaActionPerformed

    private void tblNominaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNominaMouseClicked
        // TODO add your handling code here:

        int fila = tblNomina.getSelectedRow();

        if (fila == -1) {
            return;
        }

        cmbEmpleado.setSelectedItem( tblNomina.getValueAt(fila, 1).toString());

        txtFechaEmision.setText( tblNomina.getValueAt(fila, 2).toString());

        cmbTipoPago.setSelectedItem(tblNomina.getValueAt(fila, 3).toString());

        txtMonto.setText(tblNomina.getValueAt(fila, 4).toString());

        cmbEstado.setSelectedItem( tblNomina.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tblNominaMouseClicked

    private void btnGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarNominaActionPerformed
        // TODO add your handling code here:

        // Verificar empleado
        if (cmbEmpleado.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un empleado."
            );

            return;
        }
        
        String dpi = cmbEmpleado.getSelectedItem().toString();

        String tipoPago = cmbTipoPago.getSelectedItem().toString();
        
        java.time.LocalDate fecha  = java.time.LocalDate.now();
        java.sql.Date fechaSQL = java.sql.Date.valueOf(fecha);
        NominaDAO dao = new NominaDAO();

        // Verificar que no exista
        if (dao.existeNomina(
                dpi,
                fechaSQL,
                tipoPago)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe una nómina de este tipo para este empleado en esta fecha."
            );

            return;
        }

        // Obtener salario
        double salario = dao.obtenerSalario(dpi);

        if (salario <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo obtener el salario del empleado."
            );

            return;
        }

        // Calcular porcentaje
        double porcentaje;

        if (tipoPago.equals("QUINCENA")) {

            porcentaje = 0.30;

        } else {

            porcentaje = 0.70;
        }

        // Calcular monto
        double monto = salario * porcentaje;

        // Mostrar datos
        txtFechaEmision.setText(
                fecha.toString()
        );

        txtMonto.setText(
                String.format("%.2f", monto)
        );

        cmbEstado.setSelectedItem("PENDIENTE");

        // Confirmar
        int confirmar
                = JOptionPane.showConfirmDialog(
                        this,
                        "Empleado: " + dpi
                        + "\nTipo de pago: " + tipoPago
                        + "\nSalario: Q"
                        + String.format("%.2f", salario)
                        + "\nMonto a pagar: Q"
                        + String.format("%.2f", monto)
                        + "\n\n¿Desea generar esta nómina?",
                        "Confirmar nómina",
                        JOptionPane.YES_NO_OPTION
                );

        if (confirmar != JOptionPane.YES_OPTION) {

            return;
        }

        // Registrar
        boolean registrada
                = dao.registrarNomina(
                        dpi,
                        fechaSQL,
                        tipoPago,
                        monto
                );

        if (registrada) {

            JOptionPane.showMessageDialog(
                    this,
                    "Nómina generada correctamente."
            );

            cargarTabla();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo generar la nómina."
            );
        }
    }//GEN-LAST:event_btnGenerarNominaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarNomina;
    private javax.swing.JButton btnPagarNomina;
    private javax.swing.JComboBox<String> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNomina;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tblNomina.getModel();

        // Limpiar la tabla
        modelo.setRowCount(0);

        NominaDAO dao = new NominaDAO();
        try {

            ResultSet resultado = dao.consultarNominas();

            while (resultado.next()) {
                modelo.addRow(
                        new Object[]{
                            resultado.getInt("codigo_nomina"),
                            resultado.getString("dpi_empleado"),
                            resultado.getDate("fecha_emision"),
                            resultado.getString("tipo_de_pago"),
                            resultado.getDouble("monto"),
                            resultado.getString("estado_pago")
                        }
                );
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar las nóminas."
            );

            e.printStackTrace();
        }
    }

    private void cargarCombos() {
        // Empleados activos
        cmbEmpleado.removeAllItems();

        NominaDAO dao = new NominaDAO();

        try {

            ResultSet resultado = dao.consultarEmpleadosActivos();

            while (resultado.next()) {

                String dpi = resultado.getString("dpi");

                cmbEmpleado.addItem(dpi);
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar los empleados."
            );

            e.printStackTrace();
        }

        // Tipo de pago
        cmbTipoPago.removeAllItems();

        cmbTipoPago.addItem("QUINCENA");
        cmbTipoPago.addItem("FIN_DE_MES");

        // Estado
        cmbEstado.removeAllItems();

        cmbEstado.addItem("PENDIENTE");

        // Seleccionamos PENDIENTE
        cmbEstado.setSelectedItem("PENDIENTE");

        // El estado no lo modifica el usuario
        cmbEstado.setEnabled(false);

        // El monto lo calcula el sistema
        txtMonto.setEditable(false);

        // La fecha la coloca el sistema
        txtFechaEmision.setEditable(false);

        // Colocar fecha actual
        txtFechaEmision.setText(
                java.time.LocalDate.now().toString()
        );
    }
}
