/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author fernan
 */
public class panelMesa extends javax.swing.JPanel {
    
    private int numeroMesa;
    private int capacidad;
    private String estado;
    private Runnable accionClick;
    /**
     * Creates new form panelMesa
     */
    public panelMesa() {
        initComponents();
    }
    
    public panelMesa(int numeroMesa, int capacidad, String estado) {
    initComponents();
     this.numeroMesa = numeroMesa;
    this.capacidad = capacidad;
    this.estado = estado;

    lblNumero.setText("MESA " + numeroMesa);
    lblEstado.setText(estado);
    lblCapacidad.setText("Capacidad: " + capacidad);

    actualizarEstado();
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstado = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCapacidad = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("LIBRE");
        add(lblEstado, java.awt.BorderLayout.CENTER);

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("Mesa 1");
        add(lblNumero, java.awt.BorderLayout.PAGE_START);

        lblCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapacidad.setText("Capacidad: 4");
        add(lblCapacidad, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumero;
    // End of variables declaration//GEN-END:variables
   private void agregarEventoClick() {

    java.awt.event.MouseAdapter evento =
        new java.awt.event.MouseAdapter() {

            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {

                if (accionClick != null) {
                    accionClick.run();
                }
            }
        };

    addMouseListener(evento);
    lblEstado.addMouseListener(evento);
    lblNumero.addMouseListener(evento);
    lblCapacidad.addMouseListener(evento);
}
    public void setAccionClick(Runnable accionClick) {
    this.accionClick = accionClick;
}
    
    private void actualizarEstado() {

    if (estado.equalsIgnoreCase("LIBRE")) {

        setBorder(
            javax.swing.BorderFactory.createLineBorder(
                java.awt.Color.GREEN,
                3
            )
        );

    } else if (estado.equalsIgnoreCase("OCUPADA")) {

        setBorder(
            javax.swing.BorderFactory.createLineBorder(
                java.awt.Color.RED,
                3
            )
        );
    }
}
}
