/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import ComunicacionesDAO.ProductoDAO;
import java.awt.Desktop;
import java.awt.Image;
import java.io.BufferedWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.concurrent.ExecutionException;
import javax.swing.ImageIcon;


/**
 *
 * @author fernan
 */
public class ProductoFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductoFrame
     */
    public ProductoFrame() {
        initComponents();

        cargarCategorias();
        txtCodigoProducto.setEditable(false);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFotografia = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblVistaImagen = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 190, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Categoria: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 190, 30));
        getContentPane().add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 100, 30));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 200, 30));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("fotografia: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        txtFotografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFotografiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFotografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 200, 30));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 110, 40));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 100, 40));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Precio", "Fotografia"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 680, 190));
        getContentPane().add(lblVistaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 190, 160));

        btnExportar.setText("Exportar HTML");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFotografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFotografiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFotografiaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String categoria = cmbCategoria.getSelectedItem().toString();
        String precioTexto = txtPrecio.getText().trim();
        String fotografia = txtFotografia.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el nombre del producto."
            );
            return;
        }
        if (precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el precio."
            );
            return;
        }
        double precio;
        try {
            precio = Double.parseDouble(precioTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "El precio debe ser numérico."
            );
            return;
        }
        if (precio <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "El precio debe ser mayor que cero."
            );
            return;
        }
        Producto producto = new Producto(
                        0,
                        nombre,
                        categoria,
                        precio,
                        fotografia
                );
        
        ProductoDAO dao = new ProductoDAO();
        boolean registrado = dao.insertarProducto(producto);
        if (registrado) {
            JOptionPane.showMessageDialog(
                    this,
                    "Producto registrado correctamente."
            );
            cargarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el producto."
            );
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int fila = tblProductos.getSelectedRow();

        if (fila == -1) {
            return;
        }
        txtCodigoProducto.setText( tblProductos.getValueAt(fila, 0).toString());
        txtNombre.setText( tblProductos.getValueAt(fila, 1).toString());
        cmbCategoria.setSelectedItem(tblProductos.getValueAt(fila, 2).toString());
        txtPrecio.setText(tblProductos.getValueAt(fila, 3).toString());
        Object fotografia = tblProductos.getValueAt(fila, 4);
        if (fotografia != null) {
            txtFotografia.setText(fotografia.toString());
            mostrarImagen(fotografia.toString());

        } else {
            txtFotografia.setText("");
            mostrarImagen("");
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (txtCodigoProducto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla."
            );
            return;
        }
        String nombre = txtNombre.getText().trim();
        String categoria = cmbCategoria.getSelectedItem().toString();
        String precioTexto = txtPrecio.getText().trim();
        String fotografia = txtFotografia.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío."
            );
            return;
        }
        if (precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el precio."
            );
            return;
        }
        double precio;
        try {
            precio = Double.parseDouble(precioTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser numérico.");
            return;
        }
        if (precio <= 0) {
            JOptionPane.showMessageDialog(this, "El precio debe ser mayor que cero.");
            return;
        }
        int codigo = Integer.parseInt(txtCodigoProducto.getText().trim());
        Producto producto = new Producto(
                        codigo,
                        nombre,
                        categoria,
                        precio,
                        fotografia
                );
        ProductoDAO dao = new ProductoDAO();
        boolean actualizado = dao.actualizarProducto(producto);
        if (actualizado) {
            JOptionPane.showMessageDialog(
                    this,
                    "Producto actualizado correctamente."
            );
            cargarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el producto.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        ProductoDAO dao = new ProductoDAO();

        try {
            ResultSet resultado = dao.consultarProductos();
            StringBuilder html = new StringBuilder();
            html.append("""
                    <!DOCTYPE html>
                    <html lang="es">
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">

                        <title>JavaBeans Café - Menú</title>

                        <style>
                            body {
                                font-family: Arial, sans-serif;
                                background-color: #f5f1e8;
                                margin: 0;
                                padding: 30px;
                            }

                            h1 {
                                text-align: center;
                            }

                            .menu {
                                display: grid;
                                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                                gap: 25px;
                                max-width: 1200px;
                                margin: auto;
                            }

                            .producto {
                                background-color: white;
                                border-radius: 15px;
                                padding: 20px;
                                text-align: center;
                                box-shadow: 0 4px 10px rgba(0,0,0,0.15);
                            }

                            .producto img {
                                width: 100%;
                                height: 200px;
                                object-fit: cover;
                                border-radius: 10px;
                            }

                            .producto h2 {
                                margin-bottom: 10px;
                            }

                            .categoria {
                                font-size: 14px;
                                color: #777;
                            }

                            .precio {
                                font-size: 20px;
                                font-weight: bold;
                            }
                        </style>

                    </head>

                    <body>

                        <h1>JavaBeans Café</h1>

                        <div class="menu">
                    """);

            boolean hayProductos = false;
            while (resultado.next()) {
                hayProductos = true;
                String nombre = resultado.getString("nombre");
                String categoria = resultado.getString("categoria");
                double precio = resultado.getDouble("precio");
                String fotografia = resultado.getString("fotografia");
                html.append("<div class=\"producto\">");
                html.append("<img src=\"")
                        .append(fotografia)
                        .append("\" alt=\"")
                        .append(nombre)
                        .append("\">");
                html.append("<h2>")
                        .append(nombre)
                        .append("</h2>");
                html.append("<p class=\"categoria\">")
                        .append(categoria)
                        .append("</p>");
                html.append("<p class=\"precio\">Q")
                        .append(String.format("%.2f", precio))
                        .append("</p>");
                html.append("</div>");
            }
            html.append("""
                        </div>
                    </body>
                    </html>
                    """);
            resultado.close();
            if (!hayProductos) {
                JOptionPane.showMessageDialog(
                        this,
                        "No existen productos registrados."
                );
                return;
            }

            File archivo = new File("menu.html");
            try (BufferedWriter escritor = new BufferedWriter( new FileWriter(archivo))) {

                escritor.write(html.toString());
            }
            JOptionPane.showMessageDialog(
                    this,
                    "Menú HTML exportado correctamente."
            );
            Desktop.getDesktop().open(archivo);
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al consultar los productos."
            );

            e.printStackTrace();

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo generar el archivo HTML."
            );

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVistaImagen;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtFotografia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void cargarCategorias() {
        cmbCategoria.removeAllItems();
        cmbCategoria.addItem("BEBIDA_CALIENTE");
        cmbCategoria.addItem("BEBIDA_FRIA");
        cmbCategoria.addItem("POSTRE");
        cmbCategoria.addItem("COMIDA");
    }

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();

        modelo.setRowCount(0);

        ProductoDAO dao = new ProductoDAO();

        ResultSet resultado = dao.consultarProductos();

        try {

            while (resultado.next()) {

                modelo.addRow(
                        new Object[]{
                            resultado.getInt("codigo_producto"),
                            resultado.getString("nombre"),
                            resultado.getString("categoria"),
                            resultado.getDouble("precio"),
                            resultado.getString("fotografia")
                        }
                );
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar los productos."
            );
        }
    }

    private void limpiarCampos() {
        txtCodigoProducto.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtFotografia.setText("");
    }

    private void mostrarImagen(String ruta) {

     if (ruta == null || ruta.isEmpty()) {

         lblVistaImagen.setIcon(null);
         lblVistaImagen.setText("Sin imagen");

         return;
     }

     try {

         URL url = new URL(ruta);

         ImageIcon icono = new ImageIcon(url);

         Image imagen = icono.getImage();

         Image imagenEscalada = imagen.getScaledInstance(
                 lblVistaImagen.getWidth(),
                 lblVistaImagen.getHeight(),
                 Image.SCALE_SMOOTH
         );

         lblVistaImagen.setIcon(
                 new ImageIcon(imagenEscalada)
         );

         lblVistaImagen.setText("");

     } catch (Exception e) {

         lblVistaImagen.setIcon(null);
         lblVistaImagen.setText("URL no válida");

     }
 }
}
